/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ContentIdea as PrismaContentIdea,
  Script as PrismaScript,
  TrendAnalysis as PrismaTrendAnalysis,
} from "@prisma/client";

export class ContentIdeaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ContentIdeaCountArgs, "select">
  ): Promise<number> {
    return this.prisma.contentIdea.count(args);
  }

  async contentIdeas(
    args: Prisma.ContentIdeaFindManyArgs
  ): Promise<PrismaContentIdea[]> {
    return this.prisma.contentIdea.findMany(args);
  }
  async contentIdea(
    args: Prisma.ContentIdeaFindUniqueArgs
  ): Promise<PrismaContentIdea | null> {
    return this.prisma.contentIdea.findUnique(args);
  }
  async createContentIdea(
    args: Prisma.ContentIdeaCreateArgs
  ): Promise<PrismaContentIdea> {
    return this.prisma.contentIdea.create(args);
  }
  async updateContentIdea(
    args: Prisma.ContentIdeaUpdateArgs
  ): Promise<PrismaContentIdea> {
    return this.prisma.contentIdea.update(args);
  }
  async deleteContentIdea(
    args: Prisma.ContentIdeaDeleteArgs
  ): Promise<PrismaContentIdea> {
    return this.prisma.contentIdea.delete(args);
  }

  async findScripts(
    parentId: string,
    args: Prisma.ScriptFindManyArgs
  ): Promise<PrismaScript[]> {
    return this.prisma.contentIdea
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .scripts(args);
  }

  async getTrendAnalysis(
    parentId: string
  ): Promise<PrismaTrendAnalysis | null> {
    return this.prisma.contentIdea
      .findUnique({
        where: { id: parentId },
      })
      .trendAnalysis();
  }
}
