/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TrendAnalysisService } from "../trendAnalysis.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TrendAnalysisCreateInput } from "./TrendAnalysisCreateInput";
import { TrendAnalysis } from "./TrendAnalysis";
import { TrendAnalysisFindManyArgs } from "./TrendAnalysisFindManyArgs";
import { TrendAnalysisWhereUniqueInput } from "./TrendAnalysisWhereUniqueInput";
import { TrendAnalysisUpdateInput } from "./TrendAnalysisUpdateInput";
import { ContentIdeaFindManyArgs } from "../../contentIdea/base/ContentIdeaFindManyArgs";
import { ContentIdea } from "../../contentIdea/base/ContentIdea";
import { ContentIdeaWhereUniqueInput } from "../../contentIdea/base/ContentIdeaWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TrendAnalysisControllerBase {
  constructor(
    protected readonly service: TrendAnalysisService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TrendAnalysis })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTrendAnalysis(
    @common.Body() data: TrendAnalysisCreateInput
  ): Promise<TrendAnalysis> {
    return await this.service.createTrendAnalysis({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        keywords: true,
        platform: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TrendAnalysis] })
  @ApiNestedQuery(TrendAnalysisFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trendAnalyses(
    @common.Req() request: Request
  ): Promise<TrendAnalysis[]> {
    const args = plainToClass(TrendAnalysisFindManyArgs, request.query);
    return this.service.trendAnalyses({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        keywords: true,
        platform: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TrendAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trendAnalysis(
    @common.Param() params: TrendAnalysisWhereUniqueInput
  ): Promise<TrendAnalysis | null> {
    const result = await this.service.trendAnalysis({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        keywords: true,
        platform: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TrendAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTrendAnalysis(
    @common.Param() params: TrendAnalysisWhereUniqueInput,
    @common.Body() data: TrendAnalysisUpdateInput
  ): Promise<TrendAnalysis | null> {
    try {
      return await this.service.updateTrendAnalysis({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          keywords: true,
          platform: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TrendAnalysis })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTrendAnalysis(
    @common.Param() params: TrendAnalysisWhereUniqueInput
  ): Promise<TrendAnalysis | null> {
    try {
      return await this.service.deleteTrendAnalysis({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          keywords: true,
          platform: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/contentIdeas")
  @ApiNestedQuery(ContentIdeaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ContentIdea",
    action: "read",
    possession: "any",
  })
  async findContentIdeas(
    @common.Req() request: Request,
    @common.Param() params: TrendAnalysisWhereUniqueInput
  ): Promise<ContentIdea[]> {
    const query = plainToClass(ContentIdeaFindManyArgs, request.query);
    const results = await this.service.findContentIdeas(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,

        trendAnalysis: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/contentIdeas")
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "update",
    possession: "any",
  })
  async connectContentIdeas(
    @common.Param() params: TrendAnalysisWhereUniqueInput,
    @common.Body() body: ContentIdeaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contentIdeas: {
        connect: body,
      },
    };
    await this.service.updateTrendAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/contentIdeas")
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "update",
    possession: "any",
  })
  async updateContentIdeas(
    @common.Param() params: TrendAnalysisWhereUniqueInput,
    @common.Body() body: ContentIdeaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contentIdeas: {
        set: body,
      },
    };
    await this.service.updateTrendAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/contentIdeas")
  @nestAccessControl.UseRoles({
    resource: "TrendAnalysis",
    action: "update",
    possession: "any",
  })
  async disconnectContentIdeas(
    @common.Param() params: TrendAnalysisWhereUniqueInput,
    @common.Body() body: ContentIdeaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contentIdeas: {
        disconnect: body,
      },
    };
    await this.service.updateTrendAnalysis({
      where: params,
      data,
      select: { id: true },
    });
  }
}
